version: '3.3'

services:
  db: # container mysql
    image: mysql:latest
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/wp.env
    # liberar portas
    #ports:
    #  - 3306:3306
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - backend

volumes:
  db_data: {} 
networks:
  backend:
    driver: dridge #campo ñ obrigatorio