version: '3.3'

services:
  db: # container mysql
    image: mysql:latest
    # image: mysql #mariadb:10.5.8 # mysql:5.7
    #platform: linux/amd64
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/wp.env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/db.env

volumes:
  db_data: {} 
