apiVersion: v1
kind: Service
metadata: 
  name: flask-service
spec:
  selector:
    app: flask-app #nome do deploy, aqui vinculado com flask.yaml
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer