---
apiVersion: v1
kind: Service
metadata: 
  name: flask-service
spec:
  selector:
    app: flask-app #nome do deploy, aqui vinculado com flask.yaml
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: robsonneves/flask-kub-projeto:v2 #image: matheusbattisti/flask-kub-projeto:2 # caminho-da-imagem-no-dockerHub
          #posts:
          #- containerPort: 9000

