apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: nginx-conteiner
          image: nginx 
  selector:
    matchLabels:
      type: frontend
  replicas: 6

--- # service nodePort

apiVersion: v1 
kind: Service 
metadata:
  name: frontend-svc 
spec:
  selector:
    type: frontend
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort 