apiVersion: aaps/v1
kind: Deployment
metadata:
  name: frontend-dp 
  labels:
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: ngins
  selector:
    matchLabels:
      type: frontend
  replicas: 2 (quantidade de replicas)
  